#!/bin/bash

set -euo pipefail

docker run --rm -v $PWD:/cwd \
  -e AWS_REGION=ap-southeast-2 \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
  realestate/stackup:1.4.2 \
  "$@"
