#!/bin/bash -e

cd $(dirname $0)/..

# Clean up at the end
trap "docker-compose down --volumes --remove-orphans" 0

# Create volume
docker volume create --name ivy-cache > /dev/null
docker volume create --name docker-scala-sbt-cache > /dev/null
docker volume create --name docker-scala-sbt-coursier-cache > /dev/null

# rebuild if necessary
docker-compose build dev

docker-compose up --remove-orphans dev
